test "CondIsJumping":
	spawn a pig at the event-location:
		set {_entity} to the event-entity

	set whether {_entity} is jumping to true
	assert {_entity} is jumping with "setting to true failed"
	set whether {_entity} is jumping to false
	assert {_entity} is not jumping with "setting to false failed"
	set whether {_entity} is not jumping to false
	assert {_entity} is jumping with "(negated) setting to true failed"
	set whether {_entity} is not jumping to true
	assert {_entity} is not jumping with "(negated) setting to false failed"

	delete the entity within {_entity}
