test "CondIsEating":
	spawn a panda at the event-location:
		set {_entity} to the event-entity

	set whether {_entity} is eating to true
	assert {_entity} is eating with "setting to true failed"
	set whether {_entity} is eating to false
	assert {_entity} is not eating with "setting to false failed"
	set whether {_entity} is not eating to false
	assert {_entity} is eating with "(negated) setting to true failed"
	set whether {_entity} is not eating to true
	assert {_entity} is not eating with "(negated) setting to false failed"

	delete the entity within {_entity}
