test "CondPandaIsSneezing":
	spawn a panda at the event-location:
		set {_entity} to the event-entity

	set whether {_entity} is sneezing to true
	assert {_entity} is sneezing with "setting to true failed"
	set whether {_entity} is sneezing to false
	assert {_entity} is not sneezing with "setting to false failed"
	set whether {_entity} is not sneezing to false
	assert {_entity} is sneezing with "(negated) setting to true failed"
	set whether {_entity} is not sneezing to true
	assert {_entity} is not sneezing with "(negated) setting to false failed"

	delete the entity within {_entity}
