test "CondIsScreaming":
	spawn a goat at the event-location:
		set {_entity} to the event-entity

	set whether {_entity} is screaming to true
	assert {_entity} is screaming with "setting to true failed"
	set whether {_entity} is screaming to false
	assert {_entity} is not screaming with "setting to false failed"
	set whether {_entity} is not screaming to false
	assert {_entity} is screaming with "(negated) setting to true failed"
	set whether {_entity} is not screaming to true
	assert {_entity} is not screaming with "(negated) setting to false failed"

	delete the entity within {_entity}
