test "CondIsInvulnerable" when running minecraft "1.20.6":
	assert creative is invulnerable with "Creative mode should be invulnerable"
	assert survival is not invulnerable with "Survival mode should not be invulnerable"

test "CondIsInvulnerable":
	spawn armor stand at spawn of world "world":
		make entity invulnerable
		assert entity is invulnerable with "Entity should be invulnerable"
		make entity vulnerable
		assert entity is not invulnerable with "Entity should be vulnerable"

		set whether entity is invulnerable to true
		assert entity is invulnerable with "setting to true failed"
		set whether entity is invulnerable to false
		assert entity is not invulnerable with "setting to false failed"
		set whether entity is not invulnerable to false
		assert entity is invulnerable with "(negated) setting to true failed"
		set whether entity is not invulnerable to true
		assert entity is not invulnerable with "(negated) setting to false failed"

		delete entity
	assert {_none} is not invulnerable with "Empty variable should be vulnerable"
