test "is saddled":
	spawn a horse at (spawn of world "world"):
		set {_horse} to event-entity

	spawn a pig at (spawn of world "world"):
		set {_pig} to event-entity

	equip {_horse} and {_pig} with saddle
	assert {_horse} and {_pig} are saddled with "equipping a horse or steerable with a saddle should do exactly that"

	unequip saddle from {_horse} and {_pig}
	assert {_horse} and {_pig} aren't saddled with "unequipping a saddle from a horse or steerable should do exactly that"

	delete entity within {_horse}
	delete entity within {_pig}

test "CondIsSaddled":
	spawn a pig at the event-location:
		set {_entity} to the event-entity

	set whether {_entity} is saddled to true
	assert {_entity} is saddled with "setting to true failed"
	set whether {_entity} is saddled to false
	assert {_entity} is not saddled with "setting to false failed"
	set whether {_entity} is not saddled to false
	assert {_entity} is saddled with "(negated) setting to true failed"
	set whether {_entity} is not saddled to true
	assert {_entity} is not saddled with "(negated) setting to false failed"

	delete the entity within {_entity}
