test "old custom model data":
	set {_item} to a diamond sword with model data 1
	assert {_item} has custom model data with "false negative for model data"
	clear custom model data of {_item}
	assert {_item} doesn't have custom model data with "false positive for model data"

test "new custom model data" when running minecraft "1.21.4":
	set {_item} to a diamond sword

	set full model data of {_item} to 1
	assert {_item} has custom model data with "false negative for float model data"
	clear full model data of {_item}
	assert {_item} doesn't have custom model data with "false positive for float model data"

	set full model data of {_item} to "1"
	assert {_item} has custom model data with "false negative for string model data"
	clear full model data of {_item}
	assert {_item} doesn't have custom model data with "false positive for string model data"

	set full model data of {_item} to true
	assert {_item} has custom model data with "false negative for boolean model data"
	clear full model data of {_item}
	assert {_item} doesn't have custom model data with "false positive for boolean model data"

	set full model data of {_item} to rgb(1,1,1)
	assert {_item} has custom model data with "false negative for color model data"
	clear full model data of {_item}
	assert {_item} doesn't have custom model data with "false positive for color model data"
