test "mspt" when running minecraft "1.21":
	set {_mspt::*} to average, mean, median, min, max, 95th percentile, and 1st percentile mspt measurements from the last 10 seconds
	assert size of {_mspt::*} is 7 with "wrong number of statistics!"
	assert {_mspt::1} is {_mspt::2} with "average and mean returned different values"
	assert {_mspt::4} <= {_mspt::*} with "min was not minimum value"
	assert {_mspt::5} >= {_mspt::*} with "max was not maximum value"
	assert {_mspt::6} >= {_mspt::7} with "95th percentile was not greater than 1st percentile"


	set {_mspt::*} to average, mean, median, min, max, 95th percentile, and 1st percentile mspt measurements from the last minute
	assert size of {_mspt::*} is 7 with "wrong number of statistics!"
	assert {_mspt::1} is {_mspt::2} with "average and mean returned different values"
	assert {_mspt::4} <= {_mspt::*} with "min was not minimum value"
	assert {_mspt::5} >= {_mspt::*} with "max was not maximum value"
	assert {_mspt::6} >= {_mspt::7} with "95th percentile was not greater than 1st percentile"

	set {_mspt::*} to average, mean, median, min, max, 99.9999th percentile, and 1.55th percentile mspt measurements from the last 5 minutes
	assert size of {_mspt::*} is 7 with "wrong number of statistics!"
	assert {_mspt::1} is {_mspt::2} with "average and mean returned different values"
	assert {_mspt::4} <= {_mspt::*} with "min was not minimum value"
	assert {_mspt::5} >= {_mspt::*} with "max was not maximum value"
	assert {_mspt::6} >= {_mspt::7} with "99.9999th percentile was not greater than 1.55th percentile"
