test "CondIsBaby":
	spawn a pig at the event-location:
		set {_entity} to the event-entity

	set whether {_entity} is a baby to true
	assert {_entity} is a baby with "setting to true failed"
	set whether {_entity} is a baby to false
	assert {_entity} is not a baby with "setting to false failed"
	set whether {_entity} is not a baby to false
	assert {_entity} is a baby with "(negated) setting to true failed"
	set whether {_entity} is not a baby to true
	assert {_entity} is not a baby with "(negated) setting to false failed"

	delete the entity within {_entity}
