
test "ExprItemRarity":
	set {_item} to stick

	set item rarity of {_item} to uncommon

	assert item rarity of {_item} is uncommon with "Failed to set item rarity of item"

	reset item rarity of {_item}

	assert item rarity of {_item} is not uncommon with "Failed to reset item rarity of item"
	assert item rarity of {_item} is common with "Failed to reset item rarity of item"

	set {_item2} to bedrock

	set {_inventory} to hopper inventory named "Test"

	set slot 0 of {_inventory} to {_item2}

	assert item rarity of (slot 0 of {_inventory}) is not rare with "Should not be rare"

	set item rarity of (slot 0 of {_inventory}) to rare

	assert item rarity of (slot 0 of {_inventory}) is rare with "Failed to set item rarity of item in container"

	reset item rarity of (slot 0 of {_inventory})

	assert item rarity of (slot 0 of {_inventory}) is not rare with "Failed to reset item rarity of item in container"
	assert item rarity of (slot 0 of {_inventory}) is common with "Failed to reset item rarity of item in container"

	assert item rarity of tnt is common with "Failed to get default item rarity of TnT"
	assert item rarity of enchanted golden apple is rare with "Failed to get default item rarity of Enchanted Golden Apple"
