name: When labels are modified, run actions.

on:
    issues:
        types: [labeled]

jobs:
    remove-good-first-issue-label:
        if: ${{ github.event.label.name == 'completed' || github.event.label.name == 'PR available'}}
        runs-on: ubuntu-latest
        permissions:
            issues: write
        steps:
            - uses: actions/github-script@v6
                with:
                    script: |
                        github.rest.issues.removeLabel({
                            issue_number: context.issue.number,
                            owner: context.repo.owner,
                            repo: context.repo.repo,
                            name: ["good first issue"]
                        })
