name: checkstyle

on:
    push:
        branches:
            - master
            - 'dev/**'
    pull_request:

jobs:
    build:
        if: "! contains(toJSON(github.event.commits.*.message), '[ci skip]')"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: recursive
            - name: validate gradle wrapper
              uses: gradle/wrapper-validation-action@v2
            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                  java-version: '21'
                  distribution: 'adopt'
                  cache: gradle
            - name: Grant execute permission for gradlew
              run: chmod +x gradlew
            - name: Run checkstyle
              run: ./gradlew clean checkstyleMain
            - name: Upload checkstyle report
              uses: actions/upload-artifact@v4
              if: success()
              with:
                  name: checkstyle-report
                  path: |
                    build/reports/checkstyle/*.xml
                    build/reports/checkstyle/*.html
