name: Java 8 CI (MC 1.13-1.16)

on:
    push:
        branches:
            - master
            - 'dev/**'
    pull_request:

jobs:
    build:
        if: "! contains(toJSON(github.event.commits.*.message), '[ci skip]')"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: recursive
            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                  java-version: '17'
                  distribution: 'adopt'
                  cache: gradle
            - name: Grant execute permission for gradlew
              run: chmod +x gradlew
            - name: Build Skript and run test scripts
              run: ./gradlew clean skriptTestJava8
            - name: Upload Nightly Build
              uses: actions/upload-artifact@v3
              if: success()
              with:
                  name: skript-nightly
                  path: build/libs/*
