name: Publish to maven repo

on:
    release:
        types: [published]

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: recursive
            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                  java-version: '17'
                  distribution: 'adopt'
                  cache: gradle
            - name: Publish Skript
              run: ./gradlew publish
              env:
                  MAVEN_USERNAME: ${{ secrets.REPO_USERNAME }}
                  MAVEN_PASSWORD: ${{ secrets.REPO_TOKEN }}
